#include "TF47COreScripts\configMacros.hpp"


WHITELIST(ON)
WHITELIST_SYSTEM(0)

[gator, AIR, ["air1", "air2"]] call tf47_core_whitelist_fnc_registerWhitelist;

REGISTER_SLOT_BEGIN
REGISTER_SLOT("jtac", CCT)
REGISTER_SLOT_END

/*
TICKETSYSTEM(ON)

TICKETSYSTEM_MISSIONID(1)
TICKETSYSTEM_MISSIONAME("Test Mission")

TICKETSYSTEM_DETECTION_MODE(0)

REGISTER_DEFAULT(3)

REGISTER_TICKETCOST("jtac", 5)

REGISTER_TICKETCOST(veh1, 10)
*/
